config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
	  get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
	end
  get 'comments/new'
  post 'comments/create'
  root 'welcome#index'
  get 'welcome/index'
  get 'party/index'
  get 'invited_stars/index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	paginates_per 10
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :omniauthable, omniauth_providers: [:facebook]

  def full_name
  	"#{name} #{lastname}"
  end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.encrypted_password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	  end
	end

	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		fetch_comments
	end

	def create
		params[:comment][:text] = Obscenity.sanitize(params[:comment][:text])
		Comment.create!(
			username: current_user.full_name,
			text: params[:comment][:text]
		)
		redirect_to comments_new_path
	end

	private

	def fetch_comments
		@comments = Comment.all.order(created_at: 'DESC').page params[:page]
		@comments = [] if @comments == nil
	end
end

app/controllers/invited_stars_controller.rb
class InvitedStarsController < ApplicationController
	def index
	end
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
	def index
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/invited_stars_helper.rb
module InvitedStarsHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comments.html.slim
- @comments.each do |c|
  .row
    .large-12.small-12.columns.message
      h1.small
        = c.username
      .tiny.italic
        = c.text
      span
        = "#{t('comment.ago')} #{time_ago_in_words(c.created_at)}"
  br
.row
  .center
    = paginate @comments

app/views/comments/index.html.slim
= render 'comments'

app/views/comments/new.html.slim
.row
  br
  - if current_user.present?
    = form_for :comment, url: comments_create_path, html: { class: 'center' } do |f|
      .row
        .large-6.small-6.columns.center
          = f.text_area :text, class: 'comment', placeholder: t('comment.placeholder')
          = f.submit t('comment.submit'), class: 'button message-button right'
  - else
    .row.center
      a.facebook href=user_omniauth_authorize_path(:facebook)
        .large-6.small-6.columns.facebook-login
          .large-2.small-2.columns
            h2.large.facebook-logo
              = 'f'
          .large-10.small-10.columns
            p.nav-link.facebook-login-text.justified-text
              br
              = t('comment.send_your_comment')      
  h1.medium.shadow-text
    = t('comment.title')
  - if @comments.size == 0
    .center
      = image_tag('message.png')
    p.tiny.center.grey-text
      = t('comment.no_comments')
= render 'comments'

app/views/invited_stars/index.html.slim
h1.center.medium
  = t('invited_stars.title')
.row
  .large-12.small-12.columns
    .large-4.small-4.columns
      = image_tag('beba.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.beba')
    .large-4.small-4.columns
      = image_tag('irma.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.irma')
    .large-4.small-4.columns
      = image_tag('nena.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.nena')
.row
  .large-12.small-12.columns
    .large-4.small-4.columns
      = image_tag('mario_and_stella.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.stella_and_mario')
    .large-4.small-4.columns
      = image_tag('fede_and_german.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.fede_and_german')
    .large-4.small-4.columns
      = image_tag('marisa.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.marisa')
.row
  .large-12.small-12.columns
    .large-4.small-4.columns
      = image_tag('orlando.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.orlando')
    .large-4.small-4.columns
      = image_tag('mercedes.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.mercedes')
    .large-4.small-4.columns
      = image_tag('virginia.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.virgi')
.row
  .large-12.small-12.columns
    .large-4.small-4.columns
      = image_tag('emilce.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.emilce')
    .large-4.small-4.columns
      = image_tag('lucy.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.lucy')
    .large-4.small-4.columns
      = image_tag('luli.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.luli')
.row
  .large-12.small-12.columns
    .large-4.small-4.columns
      = image_tag('willy.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.willy')
    .large-4.small-4.columns
      = image_tag('macarena.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.macarena')
    .large-4.small-4.columns
      = image_tag('mariano.png')
      p.pink-background.center.handwrite.tiny
        = t('invited_stars.mariano')

app/views/layouts/_footer.html.slim
footer.pink.footer.large-12.small-12.columns.center
  = t('footer.info').html_safe

app/views/layouts/_header.html.slim
.pink
  .fixed
    nav.top-bar.pink data-options=('sticky_on: large') data-topbar='' role='navigation'
      .large-12.small-12.columns.center
        .large-1.small-1.columns.border-right.home.home-item
          a href=root_path
            .nav-link
              = t('navbar.home')
        .large-2.small-2.columns.border-right.nav-item
          a href=party_index_path
            .nav-link
              = t('navbar.the_party')
        .large-3.small-3.columns.border-right.nav-item
          a href=invited_stars_index_path
            .nav-link
              = t('navbar.invited_stars')
        .large-2.small-2.columns.nav-item
          a href=comments_new_path
            .nav-link
              = t('navbar.messages')
        .large-4.small-4.columns.right.nav-item
          - if current_user.present?
            a href=destroy_user_session_path
              .nav-link
                = t('application.logout', name: truncate(current_user.full_name, length: 20))
          - else
            a href=user_omniauth_authorize_path(:facebook)
              .nav-link
                = t('application.login')
#owl.owl-carousel.owl-theme
  .item
    = image_tag 'back1.png', class: 'background'
  .item
    = image_tag 'back2.png', class: 'background'
  .item
    = image_tag 'back3.png', class: 'background'
  .item
    = image_tag 'back4.png', class: 'background'
  .item
    = image_tag 'back5.png', class: 'background'
  .item
    = image_tag 'back6.png', class: 'background'
  .item
    = image_tag 'back7.png', class: 'background'
  .item
    = image_tag 'back8.png', class: 'background'
h1.application-title.large.shadow-text
  = t('application.title')

app/views/layouts/application.html.slim
doctype html
html
  head
    title Florcha15
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
  	= render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/party/index.html.slim
h1.center.medium
  = t('party.title')
br
.row
  .large-12.columns
    .large-6.small-6.columns
      h3
        = t('party.party_section.title')
      p.justified-text
        = t('party.party_section.info').html_safe
    .large-6.small-6.columns
      = image_tag('saloon1.png', class: 'party-photo')
br
.row
  .large-6.small-6.columns
    = image_tag('map.png', class: 'party-photo')
  .large-6.small-6.columns
    h4
      = t('party.how_to_get.title')
    p.justified-text
      = t('party.how_to_get.info').html_safe
br
.row
  large-6.small-6.columns
    h4.center
      = t('party.dont_drive_drunk')
  .large-6.small-6.columns
    = image_tag('saloon4.png', class: 'party-photo')
br
.row
  .large-6.small-6.columns
    = image_tag('saloon5.png', class: 'party-photo')
  .large-6.small-6.columns
    h4
      = t('party.if_rains.title')
    p.justified-text
      = t('party.if_rains.info', message: link_to(t('party.if_rains.message_link'), comments_new_path)).html_safe
br
.row
  h1.center
    = t('party.photos_soon')

app/views/welcome/index.html.slim
.large-12.columns.lightgrey
  h2.tiny.center.grey-text
    = t('welcome.the_party')
  .center.grey-text
    = t('welcome.party_address').html_safe
.large-12.small-12.columns
  h2.tiny.center.grey-text
    = t('welcome.my_parents')
  .center.grey-text.minusculus
    = t('welcome.thanks')
  br
  .row
    .large-12.small-12.columns
      .large-6.small-6.columns.center
  	    = image_tag 'carlitos.png', class: 'parent_photo pink-border'
  	    p.center.grey-text.tiny
  	      = t('invited_stars.carlitos')
      .large-6.small-6.columns.center
        = image_tag 'mariela.png', class: 'parent_photo pink-border'
        p.center.grey-text.tiny
          = t('invited_stars.mariela')
  h2.tiny.center.grey-text
    = t('welcome.my_brothers')
  br
  .row
    .large-12.small-12.columns.center
      = image_tag 'brothers.png', class: 'parent_photo pink-border'
    .large-12.small-12.columns.center
      p.center.grey-text.tiny
        = t('invited_stars.brothers')
.large-12.columns.pink
  h2.tiny.center.white-text
    = t('welcome.rsvp')
  .white-text.center
    = t('welcome.rsvp_info')